---
  header_logo_url:  http://Mantophasmatodea.archive.speciesfile.org/HomePage/Mantophasmatodea/img_Logo/SiteLogo.jpg
  header_logo_text: Mantophasmatodea Species File
  header_links:
    - label: Home
      link: /

    - label: About
      link: /about
