---
metadata:
  - name: description
    content: The Mantophasmatodea Species File is a taxonomic, nomenclatural, and bibliographic database of the heelwalkers of the world, including all extant and fossil taxa.
  - name: keywords
    content: taxonomy, species, Species File Group, mantophasmatodea, heelwalkers, taxonpages, Manthophasmatodea Species File
  - name: robots
    content: follow
