---
  project_name: "Mantophasmatodea Species File"
  project_citation: "Michael D. Maehr & Heidi Hopkins. Mantophasmatodea Species File. Version 5.0/5.0. [retrieval date]. <http://Mantophasmatodea.SpeciesFile.org>"
  project_authors: "Maehr, M.D. & Hopkins, H."
  project_url: "https://mantophasmatodea.speciesfile.org"
  project_old_url: "ttps://mantophasmatodea.archive.speciesfile.org" 
  focal_taxon: "mantophasmatodea"
  focal_taxon_common_name: "heelwalkers"
  contact_email: "cockroachdoc@gmail.com"
