---
  project_name: "Mantophasmatodea Species File"
  project_citation: "Mantophasmatodea Species File"
  project_authors: "Maehr, M.D. & Hopkins, H."
  project_url: "https://mantophasmatodea.speciesfile.org"
  project_old_url: "ttps://mantophasmatodea.archive.speciesfile.org" 
  focal_taxon: "mantophasmatodea"
  focal_taxon_common_name: "heelwalkers"
  contact_email: "cockroachdoc@gmail.com"
